openapi: 3.2.0
info:
  title: ilert REST Numbers API
  description: '# Introduction

    The ilert API is a RESTful API and provides programmatic access to entities in ilert and lets you easily integrate ilert with 3rd party tools.'
  version: v2.2026.5-r.3
  x-logo:
    url: ./ilert-logo-spaced.png
    backgroundColor: '#fafafa'
    altText: ilert documentation logo
servers:
- url: /api
security:
- apiKey: []
tags:
- name: Numbers
paths:
  /numbers:
    get:
      tags:
      - Numbers
      summary: List available phone numbers that ilert uses to send voice and SMS notifications
      responses:
        '200':
          description: List of phone numbers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OutboundNumber'
      security: []
      operationId: getNumbers
      x-operation-id-source: derived
components:
  schemas:
    OutboundNumber:
      type: object
      properties:
        countryCode:
          type: string
        phoneNumber:
          type: string
        supportsInboundSms:
          type: boolean
        types:
          type: array
          items:
            type: string
            enum:
            - SMS
            - VOICE
  securitySchemes:
    apiKey:
      type: apiKey
      description: The Bearer API key of your user <a href='/api-docs/#section/Authentication'>more info</a>.
      name: Authorization
      in: header
x-original-swagger-version: '2.0'
