openapi: 3.2.0
info:
  title: ilert REST Deployment Events API
  description: '# Introduction

    The ilert API is a RESTful API and provides programmatic access to entities in ilert and lets you easily integrate ilert with 3rd party tools.'
  version: v2.2026.5-r.3
  x-logo:
    url: ./ilert-logo-spaced.png
    backgroundColor: '#fafafa'
    altText: ilert documentation logo
servers:
- url: /api
security:
- apiKey: []
tags:
- name: Deployment Events
paths:
  /deployment-events:
    post:
      tags:
      - Deployment Events
      summary: Post a deployment event to ilert
      description: Use the Deployment events API to integrate your CI & CD tools or custom deployment workflows with ilert. Create a new deployment pipeline to generate an integration key for this endpoint.
      requestBody:
        description: The event
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeploymentEvent'
        required: true
      responses:
        '202':
          description: The event has been accepted
          content: {}
      security: []
      x-codegen-request-body-name: event
      operationId: postDeploymentEvents
      x-operation-id-source: derived
components:
  schemas:
    EventLink:
      type: object
      properties:
        href:
          type: string
        text:
          type: string
    DeploymentEvent:
      type: object
      required:
      - integrationKey
      - summary
      properties:
        integrationKey:
          type: string
        summary:
          type: string
        timestamp:
          type: integer
          format: int64
        userEmail:
          description: Optional email used to map the event to a specific user in ilert
          type: string
          format: email
        customDetails:
          type: object
          additionalProperties: true
        links:
          type: array
          items:
            $ref: '#/components/schemas/EventLink'
  securitySchemes:
    apiKey:
      type: apiKey
      description: The Bearer API key of your user <a href='/api-docs/#section/Authentication'>more info</a>.
      name: Authorization
      in: header
x-original-swagger-version: '2.0'
