openapi: 3.0.1
info:
  title: ilert REST Alert Actions Series API
  description: "# Introduction\nThe ilert API is a [RESTful](https://en.wikipedia.org/wiki/Representational_state_transfer) API and provides programmatic access to entities in ilert and lets you easily integrate ilert with 3rd party tools. If you are looking to develop an inbound integration (e.g. for a monitoring tool), please use our [Events API](#tag/events). \n\nThe API supports the JSON content type for requests and responses. The response content type is requested via the HTTP Accept header (`application/json`). All resources are accessible via https and are located at `api.ilert.com/api`. \n\n You may download ilert's latest [OpenAPI.json {...} here](https://api.ilert.com/api-docs/openapi.json).\n\n If you are looking for a classic Swagger-UI view you may also open [this link](https://api.ilert.com/api-docs/swagger-ui). \n\n ## Authentication\nThe REST API accepts bearer API tokens. Each user may create API keys using the ilert web application. Note: Make sure to send the `Bearer ` prefix e.g. `Bearer APIKEY` when sending api key requests. By default, access to all resources (using any method) requires the client to be authenticated.\n\n ## Team Context\n When using API tokens, the currently selected team context of the user will not be taken into account, i.e. list results will always return all entities to which the user has a view permission. When using basic auth credentials the currently selected team context of the user will be used to filter resource results. The context may be overwritten for API key calls using the `team-context` HTTP header. Specifying `0` for ALL teams, `-1` for MY teams or a specific team id e.g. `team-context=901` to fetch results for a certain team.  \n\n ## Errors\nilert uses HTTP response codes to indicate success or failure of an API request. Codes in the 2xx range indicate success, codes in the 4xx range indicate a client error (e.g. a missing required parameter) and codes in the 5xx range indicate an error with ilert's servers. In case of an error, the response body contains the following information:\n\n Attribute     | Description \n ------------- | ------------- \n status  | the corresponsing HTTP status code  \n message  | a human readable description of the error \n code  | error code, used to identify error type  \n\n ## API Versioning\nChanges to our API are always backwards-compatible. To get more information about our API versioning and historical changes, please <a href='https://docs.ilert.com/rest-api/api-version-history' target='_blank'>take a look here</a>."
  version: v2.2026.5-r.3
  x-logo:
    url: ./ilert-logo-spaced.png
    backgroundColor: '#fafafa'
    altText: ilert documentation logo
servers:
- url: /api
security:
- apiKey: []
tags:
- name: Series
paths:
  /series/{key}:
    post:
      tags:
      - Series
      summary: Ingest a series for a metric
      description: Post a time point or multiple time points (series) to a metric. User authorization is not required instead provide the integration key of your metric.
      parameters:
      - name: key
        in: path
        description: integration key of resource
        required: true
        schema:
          type: string
      requestBody:
        description: the time point or series of time points
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SeriesOption'
        required: true
      responses:
        '202':
          description: The time points have been accepted
          content: {}
      security: []
      x-codegen-request-body-name: series
components:
  schemas:
    SeriesOption:
      type: object
      description: Can either be a single time point, omitting timestamp field is allowed as it will be replaced with now() - or a series of multiple time points
      oneOf:
      - $ref: '#/components/schemas/SingleTimePoint'
      - $ref: '#/components/schemas/MultipleTimePoint'
    MultipleTimePoint:
      type: object
      properties:
        series:
          type: array
          items:
            $ref: '#/components/schemas/SingleTimePoint'
    SingleTimePoint:
      required:
      - value
      type: object
      properties:
        timestamp:
          type: number
          description: The unix epoch second of your time point
          format: int64
        value:
          type: number
          description: Value of your time point
          format: double
  securitySchemes:
    apiKey:
      type: apiKey
      description: The Bearer API key of your user <a href='/api-docs/#section/Authentication'>more info</a>.
      name: Authorization
      in: header
x-original-swagger-version: '2.0'
